In [2]:
import numpy as np
arr = np.random.randint(0,100,1)
print(arr)
arr2 = np.random.randint(100, size=10)
print(arr2)
arr3 = np.random.randint(100, size=[3,3])
print(arr3)

[30]
[59 95 14 58 90 71 18 82  0  5]
[[48 24 54]
 [92 78 11]
 [99 99 14]]


In [4]:
arrh = np.random.choice(a=[3,5,4,6,23,45,65,76,8,3,4], size=10)
print(arrh)

[45 23  5  4  4  8  8  4 65 23]
