In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])

In [6]:
print(arr)

[1 2 3 4 5]


In [8]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [10]:
li = [1, 2, 3]
print("List multiplication: ", li * 2)
print("arr multiplication: ", arr * 2)

List multiplication:  [1, 2, 3, 1, 2, 3]
arr multiplication:  [ 2  4  6  8 10]


In [12]:
import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(10000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.5275413990020752

 Numpy operation time:  0.02935171127319336


## creating array from scratch

In [21]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("ones array: \n", ones)

full = np.full((2, 4), 9)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 10, 2) # 0 to 10 with gap of 2
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[9 9 9 9]
 [9 9 9 9]]
random array: 
 [[0.52169475 0.91561855 0.37862802]
 [0.71799505 0.74469064 0.15018292]]
sequence array: 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [24]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## array properties

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("DType:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
DType: int64


## array reshaping

In [36]:
arr = np.arange(12)
print("original array:", arr)
reshaped = arr.reshape((3, 4))
print("Print reshaped:\n", reshaped)
flattend = reshaped.flatten()
print("Flattened array:", flattend)
ravaled = reshaped.ravel() # returns view, instead of copy
print("raveled array:", ravaled)
transpose = reshaped.T
print("transpose array:\n", transpose)

original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Print reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
