# Numpy array operatons

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing:", arr[2:7])
print("With Step:", arr[1:8:2])
print("Negative indexing:", arr[-3])

Basic Slicing: [3 4 5 6 7]
With Step: [2 4 6 8]
Negative indexing: 8


In [5]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element:", arr_2d[1, 2])
print("Entire row:", arr_2d[1])
print("Entire column:", arr_2d[:, 1])

Specific element: 6
Entire row: [4 5 6]
Entire row: [2 5 8]


## Sorting

In [11]:
unsorted = np.array([3, 1, 4, 6, 9, 2, 10, 5])
print("Sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array:\n", np.sort(arr_2d_unsorted, axis=0))

Sorted array [ 1  2  3  4  5  6  9 10]
Sorted 2D array:
 [[1 1]
 [2 2]
 [3 3]]


## Filter

In [12]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers", even_numbers)

Even Numbers [2 4 6 8]


## Filter with mask

In [13]:
mask = numbers > 5
print("numbers greater than 5:", numbers[mask])

numbers greater than 5: [6 7 8 9]


## Fancy indexing vs np.where()

In [15]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("np where:", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8]),)
np where: [6 7 8 9]


In [16]:
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']


## Adding and removing data

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## array compatibility

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [24]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = ([[7], [8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [25]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print(deleted)

[1 2 4 5]
